# Generated by Django 4.1 on 2022-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtsetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default='page', max_length=150),
        ),
    ]
