# Generated by Django 4.1 on 2022-09-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nxtsetting', '0002_home_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ringtone',
            new_name='Ring',
        ),
    ]
