# Generated by Django 4.1 on 2022-08-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='media\x08n.png', upload_to='profile/'),
        ),
    ]
