# Generated by Django 4.1 on 2022-08-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='hello', max_length=150),
            preserve_default=False,
        ),
    ]
