# Generated by Django 4.1 on 2022-08-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insta',
            field=models.URLField(default='https://www.instagram.com/_dhirz/', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.URLField(default='https://www.instagram.com/_dhirz/', max_length=150),
        ),
    ]
