# Generated by Django 4.1 on 2022-08-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_insta_user_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rupees', models.IntegerField(default=0)),
                ('reward_type', models.CharField(choices=[('Paytm', 'Paytm'), ('Points', 'Points')], default='No', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
