# Generated by Django 4.1 on 2022-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_plans_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='rupees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
