# Generated by Django 4.1 on 2022-08-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_plans_point_alter_plans_rupees'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='rupees_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='rupees_point_cent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
