# Generated by Django 4.1 on 2022-08-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_plans_rupees_point_cent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='rupees_point',
        ),
    ]
