# Generated by Django 4.1 on 2022-08-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_plans_rupees_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paytm_num',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
