# Generated by Django 4.1 on 2022-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_payment_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='inr',
            field=models.IntegerField(default=1),
        ),
    ]
